name: camapp-live-detection
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - PySide6>=6.6.0
      - pypylon>=2.0.0
      - flirpy>=0.4.0
      - numpy>=1.24.0,<2
      - scipy
      - pillow
      - torch
      - torchvision
      - rfdetr
      - ultralytics
      - pandas>=2.0.0
      - opencv-python>=4.8.0,<4.12
      - pyfirmata>=1.1.0
      - pyqtgraph>=0.13.0
      - pyserial
      - matplotlib
      - pyinstaller>=6.6.0
